work:
  theapp:
    external:
      pokeapi:
        uri: 'https://pokeapi.co/api/v2'
        species: '/pokemon-species'
        pokemon-species: '/pokemon-species/{id}'
        pokemon: '/pokemon/{id}'
        limit: 20


server:
  port: ${PORT:9090}
  error:
    whitelabel:
      enabled: false

logging:
  level:
    pokeapi.work.theapp.demo: DEBUG
    web: DEBUG

spring:
  thymeleaf:
    cache: false
