name: CI

on:
  push:
    branches:
      - development

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Unit tests
        id: unit-test
        run: gradle -q test --tests "pokeapi.work.theapp.demo.unit.*"

      - name: Integration tests
        id: integration-test
        run: gradle -q test --tests "pokeapi.work.theapp.demo.integration.*"

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: failed-tests-report
          path: ./build/reports/

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build assets
        run: npm ci & npm run build

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ""
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Push image to Heroku Registry
        run: gradle -q jib --image registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web -Djib.to.auth.username=${{ secrets.HEROKU_EMAIL }} -Djib.to.auth.password=${{ secrets.HEROKU_API_KEY }}

      - name: Release image
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}